spring:
    datasource:
        username: credential_info
        password: credential_info
        url: jdbc:mysql://localhost:3306/credential_info
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    
    sql:
        init:
            mode: never

logging:
    level:
        org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG


